#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBanVeXeKhach")]
	public partial class QuanLyNhaXeDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChiTietVe(ChiTietVe instance);
    partial void UpdateChiTietVe(ChiTietVe instance);
    partial void DeleteChiTietVe(ChiTietVe instance);
    partial void InsertXe(Xe instance);
    partial void UpdateXe(Xe instance);
    partial void DeleteXe(Xe instance);
    partial void InsertDiaDiem(DiaDiem instance);
    partial void UpdateDiaDiem(DiaDiem instance);
    partial void DeleteDiaDiem(DiaDiem instance);
    partial void InsertGHE(GHE instance);
    partial void UpdateGHE(GHE instance);
    partial void DeleteGHE(GHE instance);
    partial void InsertLichTrinh(LichTrinh instance);
    partial void UpdateLichTrinh(LichTrinh instance);
    partial void DeleteLichTrinh(LichTrinh instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertTHEMTRAMDUNGCHAN(THEMTRAMDUNGCHAN instance);
    partial void UpdateTHEMTRAMDUNGCHAN(THEMTRAMDUNGCHAN instance);
    partial void DeleteTHEMTRAMDUNGCHAN(THEMTRAMDUNGCHAN instance);
    partial void InsertTRAMDUNGCHAN(TRAMDUNGCHAN instance);
    partial void UpdateTRAMDUNGCHAN(TRAMDUNGCHAN instance);
    partial void DeleteTRAMDUNGCHAN(TRAMDUNGCHAN instance);
    partial void InsertTuyenDuong(TuyenDuong instance);
    partial void UpdateTuyenDuong(TuyenDuong instance);
    partial void DeleteTuyenDuong(TuyenDuong instance);
    partial void InsertVe(Ve instance);
    partial void UpdateVe(Ve instance);
    partial void DeleteVe(Ve instance);
    #endregion
		
		public QuanLyNhaXeDataContext() : 
				base(global::DTO.Properties.Settings.Default.QuanLyBanVeXeKhachConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaXeDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaXeDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaXeDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyNhaXeDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChiTietVe> ChiTietVes
		{
			get
			{
				return this.GetTable<ChiTietVe>();
			}
		}
		
		public System.Data.Linq.Table<Xe> Xes
		{
			get
			{
				return this.GetTable<Xe>();
			}
		}
		
		public System.Data.Linq.Table<DiaDiem> DiaDiems
		{
			get
			{
				return this.GetTable<DiaDiem>();
			}
		}
		
		public System.Data.Linq.Table<GHE> GHEs
		{
			get
			{
				return this.GetTable<GHE>();
			}
		}
		
		public System.Data.Linq.Table<LichTrinh> LichTrinhs
		{
			get
			{
				return this.GetTable<LichTrinh>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<THEMTRAMDUNGCHAN> THEMTRAMDUNGCHANs
		{
			get
			{
				return this.GetTable<THEMTRAMDUNGCHAN>();
			}
		}
		
		public System.Data.Linq.Table<TRAMDUNGCHAN> TRAMDUNGCHANs
		{
			get
			{
				return this.GetTable<TRAMDUNGCHAN>();
			}
		}
		
		public System.Data.Linq.Table<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this.GetTable<TuyenDuong>();
			}
		}
		
		public System.Data.Linq.Table<Ve> Ves
		{
			get
			{
				return this.GetTable<Ve>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ThemNhanVien")]
		public int ThemNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERNAME", DbType="NVarChar(128)")] string uSERNAME, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MAT_KHAU", DbType="NVarChar(128)")] string mAT_KHAU, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HOTEN", DbType="NVarChar(128)")] string hOTEN, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SO_DT", DbType="NVarChar(128)")] string sO_DT, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="GIOITINH", DbType="NVarChar(5)")] string gIOITINH, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIACHI", DbType="NVarChar(128)")] string dIACHI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="LOAINV", DbType="NVarChar(128)")] string lOAINV)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSERNAME, mAT_KHAU, hOTEN, sO_DT, gIOITINH, dIACHI, lOAINV);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ChonXe", IsComposable=true)]
		public System.Nullable<bool> ChonXe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(128)")] string malt)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), malt).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.LayDanhSachXeCoTheGan", IsComposable=true)]
		public IQueryable<LayDanhSachXeCoTheGanResult> LayDanhSachXeCoTheGan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> ngaykhoihanh)
		{
			return this.CreateMethodCallQuery<LayDanhSachXeCoTheGanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ngaykhoihanh);
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietVe")]
	public partial class ChiTietVe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_VE;
		
		private int _ID_GHE;
		
		private EntityRef<GHE> _GHE;
		
		private EntityRef<Ve> _Ve;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VEChanging(string value);
    partial void OnID_VEChanged();
    partial void OnID_GHEChanging(int value);
    partial void OnID_GHEChanged();
    #endregion
		
		public ChiTietVe()
		{
			this._GHE = default(EntityRef<GHE>);
			this._Ve = default(EntityRef<Ve>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VE", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_VE
		{
			get
			{
				return this._ID_VE;
			}
			set
			{
				if ((this._ID_VE != value))
				{
					if (this._Ve.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_VEChanging(value);
					this.SendPropertyChanging();
					this._ID_VE = value;
					this.SendPropertyChanged("ID_VE");
					this.OnID_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GHE", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID_GHE
		{
			get
			{
				return this._ID_GHE;
			}
			set
			{
				if ((this._ID_GHE != value))
				{
					if (this._GHE.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_GHEChanging(value);
					this.SendPropertyChanging();
					this._ID_GHE = value;
					this.SendPropertyChanged("ID_GHE");
					this.OnID_GHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GHE_ChiTietVe", Storage="_GHE", ThisKey="ID_GHE", OtherKey="ID_GHE", IsForeignKey=true)]
		public GHE GHE
		{
			get
			{
				return this._GHE.Entity;
			}
			set
			{
				GHE previousValue = this._GHE.Entity;
				if (((previousValue != value) 
							|| (this._GHE.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GHE.Entity = null;
						previousValue.ChiTietVes.Remove(this);
					}
					this._GHE.Entity = value;
					if ((value != null))
					{
						value.ChiTietVes.Add(this);
						this._ID_GHE = value.ID_GHE;
					}
					else
					{
						this._ID_GHE = default(int);
					}
					this.SendPropertyChanged("GHE");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ve_ChiTietVe", Storage="_Ve", ThisKey="ID_VE", OtherKey="ID_VE", IsForeignKey=true)]
		public Ve Ve
		{
			get
			{
				return this._Ve.Entity;
			}
			set
			{
				Ve previousValue = this._Ve.Entity;
				if (((previousValue != value) 
							|| (this._Ve.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Ve.Entity = null;
						previousValue.ChiTietVes.Remove(this);
					}
					this._Ve.Entity = value;
					if ((value != null))
					{
						value.ChiTietVes.Add(this);
						this._ID_VE = value.ID_VE;
					}
					else
					{
						this._ID_VE = default(string);
					}
					this.SendPropertyChanged("Ve");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Xe")]
	public partial class Xe : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_XE;
		
		private string _BIEN_SO_XE;
		
		private int _SO_GHE;
		
		private System.DateTime _NGAY_THEM;
		
		private EntitySet<LichTrinh> _LichTrinhs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_XEChanging(int value);
    partial void OnID_XEChanged();
    partial void OnBIEN_SO_XEChanging(string value);
    partial void OnBIEN_SO_XEChanged();
    partial void OnSO_GHEChanging(int value);
    partial void OnSO_GHEChanged();
    partial void OnNGAY_THEMChanging(System.DateTime value);
    partial void OnNGAY_THEMChanged();
    #endregion
		
		public Xe()
		{
			this._LichTrinhs = new EntitySet<LichTrinh>(new Action<LichTrinh>(this.attach_LichTrinhs), new Action<LichTrinh>(this.detach_LichTrinhs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_XE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_XE
		{
			get
			{
				return this._ID_XE;
			}
			set
			{
				if ((this._ID_XE != value))
				{
					this.OnID_XEChanging(value);
					this.SendPropertyChanging();
					this._ID_XE = value;
					this.SendPropertyChanged("ID_XE");
					this.OnID_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BIEN_SO_XE", DbType="VarChar(128)")]
		public string BIEN_SO_XE
		{
			get
			{
				return this._BIEN_SO_XE;
			}
			set
			{
				if ((this._BIEN_SO_XE != value))
				{
					this.OnBIEN_SO_XEChanging(value);
					this.SendPropertyChanging();
					this._BIEN_SO_XE = value;
					this.SendPropertyChanged("BIEN_SO_XE");
					this.OnBIEN_SO_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_GHE", DbType="Int NOT NULL")]
		public int SO_GHE
		{
			get
			{
				return this._SO_GHE;
			}
			set
			{
				if ((this._SO_GHE != value))
				{
					this.OnSO_GHEChanging(value);
					this.SendPropertyChanging();
					this._SO_GHE = value;
					this.SendPropertyChanged("SO_GHE");
					this.OnSO_GHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_THEM", DbType="DateTime NOT NULL")]
		public System.DateTime NGAY_THEM
		{
			get
			{
				return this._NGAY_THEM;
			}
			set
			{
				if ((this._NGAY_THEM != value))
				{
					this.OnNGAY_THEMChanging(value);
					this.SendPropertyChanging();
					this._NGAY_THEM = value;
					this.SendPropertyChanged("NGAY_THEM");
					this.OnNGAY_THEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_LichTrinh", Storage="_LichTrinhs", ThisKey="ID_XE", OtherKey="ID_XE")]
		public EntitySet<LichTrinh> LichTrinhs
		{
			get
			{
				return this._LichTrinhs;
			}
			set
			{
				this._LichTrinhs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.Xe = this;
		}
		
		private void detach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.Xe = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DiaDiem")]
	public partial class DiaDiem : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DIADIEM;
		
		private string _TEN_TINH_THANH;
		
		private EntitySet<TRAMDUNGCHAN> _TRAMDUNGCHANs;
		
		private EntitySet<TuyenDuong> _TuyenDuongs;
		
		private EntitySet<TuyenDuong> _TuyenDuongs1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DIADIEMChanging(int value);
    partial void OnID_DIADIEMChanged();
    partial void OnTEN_TINH_THANHChanging(string value);
    partial void OnTEN_TINH_THANHChanged();
    #endregion
		
		public DiaDiem()
		{
			this._TRAMDUNGCHANs = new EntitySet<TRAMDUNGCHAN>(new Action<TRAMDUNGCHAN>(this.attach_TRAMDUNGCHANs), new Action<TRAMDUNGCHAN>(this.detach_TRAMDUNGCHANs));
			this._TuyenDuongs = new EntitySet<TuyenDuong>(new Action<TuyenDuong>(this.attach_TuyenDuongs), new Action<TuyenDuong>(this.detach_TuyenDuongs));
			this._TuyenDuongs1 = new EntitySet<TuyenDuong>(new Action<TuyenDuong>(this.attach_TuyenDuongs1), new Action<TuyenDuong>(this.detach_TuyenDuongs1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DIADIEM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DIADIEM
		{
			get
			{
				return this._ID_DIADIEM;
			}
			set
			{
				if ((this._ID_DIADIEM != value))
				{
					this.OnID_DIADIEMChanging(value);
					this.SendPropertyChanging();
					this._ID_DIADIEM = value;
					this.SendPropertyChanged("ID_DIADIEM");
					this.OnID_DIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TINH_THANH", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TEN_TINH_THANH
		{
			get
			{
				return this._TEN_TINH_THANH;
			}
			set
			{
				if ((this._TEN_TINH_THANH != value))
				{
					this.OnTEN_TINH_THANHChanging(value);
					this.SendPropertyChanging();
					this._TEN_TINH_THANH = value;
					this.SendPropertyChanged("TEN_TINH_THANH");
					this.OnTEN_TINH_THANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TRAMDUNGCHAN", Storage="_TRAMDUNGCHANs", ThisKey="ID_DIADIEM", OtherKey="ID_DIADIEM")]
		public EntitySet<TRAMDUNGCHAN> TRAMDUNGCHANs
		{
			get
			{
				return this._TRAMDUNGCHANs;
			}
			set
			{
				this._TRAMDUNGCHANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TuyenDuong", Storage="_TuyenDuongs", ThisKey="ID_DIADIEM", OtherKey="DIEM_DAU")]
		public EntitySet<TuyenDuong> TuyenDuongs
		{
			get
			{
				return this._TuyenDuongs;
			}
			set
			{
				this._TuyenDuongs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TuyenDuong1", Storage="_TuyenDuongs1", ThisKey="ID_DIADIEM", OtherKey="DIEM_CUOI")]
		public EntitySet<TuyenDuong> TuyenDuongs1
		{
			get
			{
				return this._TuyenDuongs1;
			}
			set
			{
				this._TuyenDuongs1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TRAMDUNGCHANs(TRAMDUNGCHAN entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_TRAMDUNGCHANs(TRAMDUNGCHAN entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
		
		private void attach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = this;
		}
		
		private void detach_TuyenDuongs(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem = null;
		}
		
		private void attach_TuyenDuongs1(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem1 = this;
		}
		
		private void detach_TuyenDuongs1(TuyenDuong entity)
		{
			this.SendPropertyChanging();
			entity.DiaDiem1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GHE")]
	public partial class GHE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_GHE;
		
		private string _VI_TRI_NGOI;
		
		private string _MA_LICH_TRINH;
		
		private string _TRANG_THAI;
		
		private EntitySet<ChiTietVe> _ChiTietVes;
		
		private EntityRef<LichTrinh> _LichTrinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_GHEChanging(int value);
    partial void OnID_GHEChanged();
    partial void OnVI_TRI_NGOIChanging(string value);
    partial void OnVI_TRI_NGOIChanged();
    partial void OnMA_LICH_TRINHChanging(string value);
    partial void OnMA_LICH_TRINHChanged();
    partial void OnTRANG_THAIChanging(string value);
    partial void OnTRANG_THAIChanged();
    #endregion
		
		public GHE()
		{
			this._ChiTietVes = new EntitySet<ChiTietVe>(new Action<ChiTietVe>(this.attach_ChiTietVes), new Action<ChiTietVe>(this.detach_ChiTietVes));
			this._LichTrinh = default(EntityRef<LichTrinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_GHE", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_GHE
		{
			get
			{
				return this._ID_GHE;
			}
			set
			{
				if ((this._ID_GHE != value))
				{
					this.OnID_GHEChanging(value);
					this.SendPropertyChanging();
					this._ID_GHE = value;
					this.SendPropertyChanged("ID_GHE");
					this.OnID_GHEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VI_TRI_NGOI", DbType="VarChar(10)")]
		public string VI_TRI_NGOI
		{
			get
			{
				return this._VI_TRI_NGOI;
			}
			set
			{
				if ((this._VI_TRI_NGOI != value))
				{
					this.OnVI_TRI_NGOIChanging(value);
					this.SendPropertyChanging();
					this._VI_TRI_NGOI = value;
					this.SendPropertyChanged("VI_TRI_NGOI");
					this.OnVI_TRI_NGOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LICH_TRINH", DbType="VarChar(128)")]
		public string MA_LICH_TRINH
		{
			get
			{
				return this._MA_LICH_TRINH;
			}
			set
			{
				if ((this._MA_LICH_TRINH != value))
				{
					if (this._LichTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._MA_LICH_TRINH = value;
					this.SendPropertyChanged("MA_LICH_TRINH");
					this.OnMA_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANG_THAI", DbType="NVarChar(128)")]
		public string TRANG_THAI
		{
			get
			{
				return this._TRANG_THAI;
			}
			set
			{
				if ((this._TRANG_THAI != value))
				{
					this.OnTRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._TRANG_THAI = value;
					this.SendPropertyChanged("TRANG_THAI");
					this.OnTRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GHE_ChiTietVe", Storage="_ChiTietVes", ThisKey="ID_GHE", OtherKey="ID_GHE")]
		public EntitySet<ChiTietVe> ChiTietVes
		{
			get
			{
				return this._ChiTietVes;
			}
			set
			{
				this._ChiTietVes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_GHE", Storage="_LichTrinh", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH", IsForeignKey=true)]
		public LichTrinh LichTrinh
		{
			get
			{
				return this._LichTrinh.Entity;
			}
			set
			{
				LichTrinh previousValue = this._LichTrinh.Entity;
				if (((previousValue != value) 
							|| (this._LichTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTrinh.Entity = null;
						previousValue.GHEs.Remove(this);
					}
					this._LichTrinh.Entity = value;
					if ((value != null))
					{
						value.GHEs.Add(this);
						this._MA_LICH_TRINH = value.MA_LICH_TRINH;
					}
					else
					{
						this._MA_LICH_TRINH = default(string);
					}
					this.SendPropertyChanged("LichTrinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietVes(ChiTietVe entity)
		{
			this.SendPropertyChanging();
			entity.GHE = this;
		}
		
		private void detach_ChiTietVes(ChiTietVe entity)
		{
			this.SendPropertyChanging();
			entity.GHE = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LichTrinh")]
	public partial class LichTrinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MA_LICH_TRINH;
		
		private int _ID_TUYEN_DUONG;
		
		private System.DateTime _KHOI_HANH;
		
		private System.Nullable<System.DateTime> _KET_THUC;
		
		private double _GIA_VE;
		
		private int _ID_XE;
		
		private System.Nullable<int> _SOGHETRONG;
		
		private System.DateTime _NGAY_TAO_LICH_TRINH;
		
		private EntitySet<GHE> _GHEs;
		
		private EntitySet<THEMTRAMDUNGCHAN> _THEMTRAMDUNGCHANs;
		
		private EntitySet<Ve> _Ves;
		
		private EntityRef<Xe> _Xe;
		
		private EntityRef<TuyenDuong> _TuyenDuong;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMA_LICH_TRINHChanging(string value);
    partial void OnMA_LICH_TRINHChanged();
    partial void OnID_TUYEN_DUONGChanging(int value);
    partial void OnID_TUYEN_DUONGChanged();
    partial void OnKHOI_HANHChanging(System.DateTime value);
    partial void OnKHOI_HANHChanged();
    partial void OnKET_THUCChanging(System.Nullable<System.DateTime> value);
    partial void OnKET_THUCChanged();
    partial void OnGIA_VEChanging(double value);
    partial void OnGIA_VEChanged();
    partial void OnID_XEChanging(int value);
    partial void OnID_XEChanged();
    partial void OnSOGHETRONGChanging(System.Nullable<int> value);
    partial void OnSOGHETRONGChanged();
    partial void OnNGAY_TAO_LICH_TRINHChanging(System.DateTime value);
    partial void OnNGAY_TAO_LICH_TRINHChanged();
    #endregion
		
		public LichTrinh()
		{
			this._GHEs = new EntitySet<GHE>(new Action<GHE>(this.attach_GHEs), new Action<GHE>(this.detach_GHEs));
			this._THEMTRAMDUNGCHANs = new EntitySet<THEMTRAMDUNGCHAN>(new Action<THEMTRAMDUNGCHAN>(this.attach_THEMTRAMDUNGCHANs), new Action<THEMTRAMDUNGCHAN>(this.detach_THEMTRAMDUNGCHANs));
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._Xe = default(EntityRef<Xe>);
			this._TuyenDuong = default(EntityRef<TuyenDuong>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_LICH_TRINH
		{
			get
			{
				return this._MA_LICH_TRINH;
			}
			set
			{
				if ((this._MA_LICH_TRINH != value))
				{
					this.OnMA_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._MA_LICH_TRINH = value;
					this.SendPropertyChanged("MA_LICH_TRINH");
					this.OnMA_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TUYEN_DUONG", DbType="Int NOT NULL")]
		public int ID_TUYEN_DUONG
		{
			get
			{
				return this._ID_TUYEN_DUONG;
			}
			set
			{
				if ((this._ID_TUYEN_DUONG != value))
				{
					if (this._TuyenDuong.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TUYEN_DUONGChanging(value);
					this.SendPropertyChanging();
					this._ID_TUYEN_DUONG = value;
					this.SendPropertyChanged("ID_TUYEN_DUONG");
					this.OnID_TUYEN_DUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOI_HANH", DbType="DateTime NOT NULL")]
		public System.DateTime KHOI_HANH
		{
			get
			{
				return this._KHOI_HANH;
			}
			set
			{
				if ((this._KHOI_HANH != value))
				{
					this.OnKHOI_HANHChanging(value);
					this.SendPropertyChanging();
					this._KHOI_HANH = value;
					this.SendPropertyChanged("KHOI_HANH");
					this.OnKHOI_HANHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KET_THUC", DbType="DateTime")]
		public System.Nullable<System.DateTime> KET_THUC
		{
			get
			{
				return this._KET_THUC;
			}
			set
			{
				if ((this._KET_THUC != value))
				{
					this.OnKET_THUCChanging(value);
					this.SendPropertyChanging();
					this._KET_THUC = value;
					this.SendPropertyChanged("KET_THUC");
					this.OnKET_THUCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIA_VE", DbType="Float NOT NULL")]
		public double GIA_VE
		{
			get
			{
				return this._GIA_VE;
			}
			set
			{
				if ((this._GIA_VE != value))
				{
					this.OnGIA_VEChanging(value);
					this.SendPropertyChanging();
					this._GIA_VE = value;
					this.SendPropertyChanged("GIA_VE");
					this.OnGIA_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_XE", DbType="Int NOT NULL")]
		public int ID_XE
		{
			get
			{
				return this._ID_XE;
			}
			set
			{
				if ((this._ID_XE != value))
				{
					if (this._Xe.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_XEChanging(value);
					this.SendPropertyChanging();
					this._ID_XE = value;
					this.SendPropertyChanged("ID_XE");
					this.OnID_XEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOGHETRONG", DbType="Int")]
		public System.Nullable<int> SOGHETRONG
		{
			get
			{
				return this._SOGHETRONG;
			}
			set
			{
				if ((this._SOGHETRONG != value))
				{
					this.OnSOGHETRONGChanging(value);
					this.SendPropertyChanging();
					this._SOGHETRONG = value;
					this.SendPropertyChanged("SOGHETRONG");
					this.OnSOGHETRONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_TAO_LICH_TRINH", DbType="DateTime NOT NULL")]
		public System.DateTime NGAY_TAO_LICH_TRINH
		{
			get
			{
				return this._NGAY_TAO_LICH_TRINH;
			}
			set
			{
				if ((this._NGAY_TAO_LICH_TRINH != value))
				{
					this.OnNGAY_TAO_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._NGAY_TAO_LICH_TRINH = value;
					this.SendPropertyChanged("NGAY_TAO_LICH_TRINH");
					this.OnNGAY_TAO_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_GHE", Storage="_GHEs", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH")]
		public EntitySet<GHE> GHEs
		{
			get
			{
				return this._GHEs;
			}
			set
			{
				this._GHEs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_THEMTRAMDUNGCHAN", Storage="_THEMTRAMDUNGCHANs", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH")]
		public EntitySet<THEMTRAMDUNGCHAN> THEMTRAMDUNGCHANs
		{
			get
			{
				return this._THEMTRAMDUNGCHANs;
			}
			set
			{
				this._THEMTRAMDUNGCHANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_Ve", Storage="_Ves", ThisKey="MA_LICH_TRINH", OtherKey="ID_LICH_TRINH")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Xe_LichTrinh", Storage="_Xe", ThisKey="ID_XE", OtherKey="ID_XE", IsForeignKey=true)]
		public Xe Xe
		{
			get
			{
				return this._Xe.Entity;
			}
			set
			{
				Xe previousValue = this._Xe.Entity;
				if (((previousValue != value) 
							|| (this._Xe.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Xe.Entity = null;
						previousValue.LichTrinhs.Remove(this);
					}
					this._Xe.Entity = value;
					if ((value != null))
					{
						value.LichTrinhs.Add(this);
						this._ID_XE = value.ID_XE;
					}
					else
					{
						this._ID_XE = default(int);
					}
					this.SendPropertyChanged("Xe");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenDuong_LichTrinh", Storage="_TuyenDuong", ThisKey="ID_TUYEN_DUONG", OtherKey="ID_TUYEN", IsForeignKey=true)]
		public TuyenDuong TuyenDuong
		{
			get
			{
				return this._TuyenDuong.Entity;
			}
			set
			{
				TuyenDuong previousValue = this._TuyenDuong.Entity;
				if (((previousValue != value) 
							|| (this._TuyenDuong.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TuyenDuong.Entity = null;
						previousValue.LichTrinhs.Remove(this);
					}
					this._TuyenDuong.Entity = value;
					if ((value != null))
					{
						value.LichTrinhs.Add(this);
						this._ID_TUYEN_DUONG = value.ID_TUYEN;
					}
					else
					{
						this._ID_TUYEN_DUONG = default(int);
					}
					this.SendPropertyChanged("TuyenDuong");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_GHEs(GHE entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = this;
		}
		
		private void detach_GHEs(GHE entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = null;
		}
		
		private void attach_THEMTRAMDUNGCHANs(THEMTRAMDUNGCHAN entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = this;
		}
		
		private void detach_THEMTRAMDUNGCHANs(THEMTRAMDUNGCHAN entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = null;
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.LichTrinh = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _USERNAME;
		
		private string _MAT_KHAU;
		
		private string _HOTEN;
		
		private string _SO_DT;
		
		private string _GIOITINH;
		
		private string _DIACHI;
		
		private string _LOAINV;
		
		private EntitySet<Ve> _Ves;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUSERNAMEChanging(string value);
    partial void OnUSERNAMEChanged();
    partial void OnMAT_KHAUChanging(string value);
    partial void OnMAT_KHAUChanged();
    partial void OnHOTENChanging(string value);
    partial void OnHOTENChanged();
    partial void OnSO_DTChanging(string value);
    partial void OnSO_DTChanged();
    partial void OnGIOITINHChanging(string value);
    partial void OnGIOITINHChanged();
    partial void OnDIACHIChanging(string value);
    partial void OnDIACHIChanged();
    partial void OnLOAINVChanging(string value);
    partial void OnLOAINVChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_USERNAME", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string USERNAME
		{
			get
			{
				return this._USERNAME;
			}
			set
			{
				if ((this._USERNAME != value))
				{
					this.OnUSERNAMEChanging(value);
					this.SendPropertyChanging();
					this._USERNAME = value;
					this.SendPropertyChanged("USERNAME");
					this.OnUSERNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAT_KHAU", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string MAT_KHAU
		{
			get
			{
				return this._MAT_KHAU;
			}
			set
			{
				if ((this._MAT_KHAU != value))
				{
					this.OnMAT_KHAUChanging(value);
					this.SendPropertyChanging();
					this._MAT_KHAU = value;
					this.SendPropertyChanged("MAT_KHAU");
					this.OnMAT_KHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOTEN", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string HOTEN
		{
			get
			{
				return this._HOTEN;
			}
			set
			{
				if ((this._HOTEN != value))
				{
					this.OnHOTENChanging(value);
					this.SendPropertyChanging();
					this._HOTEN = value;
					this.SendPropertyChanged("HOTEN");
					this.OnHOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SO_DT", DbType="VarChar(128)")]
		public string SO_DT
		{
			get
			{
				return this._SO_DT;
			}
			set
			{
				if ((this._SO_DT != value))
				{
					this.OnSO_DTChanging(value);
					this.SendPropertyChanging();
					this._SO_DT = value;
					this.SendPropertyChanged("SO_DT");
					this.OnSO_DTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIOITINH", DbType="NVarChar(5) NOT NULL", CanBeNull=false)]
		public string GIOITINH
		{
			get
			{
				return this._GIOITINH;
			}
			set
			{
				if ((this._GIOITINH != value))
				{
					this.OnGIOITINHChanging(value);
					this.SendPropertyChanging();
					this._GIOITINH = value;
					this.SendPropertyChanged("GIOITINH");
					this.OnGIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIACHI", DbType="NVarChar(128)")]
		public string DIACHI
		{
			get
			{
				return this._DIACHI;
			}
			set
			{
				if ((this._DIACHI != value))
				{
					this.OnDIACHIChanging(value);
					this.SendPropertyChanging();
					this._DIACHI = value;
					this.SendPropertyChanged("DIACHI");
					this.OnDIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOAINV", DbType="NVarChar(128)")]
		public string LOAINV
		{
			get
			{
				return this._LOAINV;
			}
			set
			{
				if ((this._LOAINV != value))
				{
					this.OnLOAINVChanging(value);
					this.SendPropertyChanging();
					this._LOAINV = value;
					this.SendPropertyChanged("LOAINV");
					this.OnLOAINVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_Ve", Storage="_Ves", ThisKey="USERNAME", OtherKey="NHAN_VIEN_TAO")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THEMTRAMDUNGCHAN")]
	public partial class THEMTRAMDUNGCHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_TramDungChan;
		
		private string _MA_LICH_TRINH;
		
		private EntityRef<LichTrinh> _LichTrinh;
		
		private EntityRef<TRAMDUNGCHAN> _TRAMDUNGCHAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TramDungChanChanging(string value);
    partial void OnID_TramDungChanChanged();
    partial void OnMA_LICH_TRINHChanging(string value);
    partial void OnMA_LICH_TRINHChanged();
    #endregion
		
		public THEMTRAMDUNGCHAN()
		{
			this._LichTrinh = default(EntityRef<LichTrinh>);
			this._TRAMDUNGCHAN = default(EntityRef<TRAMDUNGCHAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TramDungChan", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_TramDungChan
		{
			get
			{
				return this._ID_TramDungChan;
			}
			set
			{
				if ((this._ID_TramDungChan != value))
				{
					if (this._TRAMDUNGCHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_TramDungChanChanging(value);
					this.SendPropertyChanging();
					this._ID_TramDungChan = value;
					this.SendPropertyChanged("ID_TramDungChan");
					this.OnID_TramDungChanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MA_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MA_LICH_TRINH
		{
			get
			{
				return this._MA_LICH_TRINH;
			}
			set
			{
				if ((this._MA_LICH_TRINH != value))
				{
					if (this._LichTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMA_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._MA_LICH_TRINH = value;
					this.SendPropertyChanged("MA_LICH_TRINH");
					this.OnMA_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_THEMTRAMDUNGCHAN", Storage="_LichTrinh", ThisKey="MA_LICH_TRINH", OtherKey="MA_LICH_TRINH", IsForeignKey=true)]
		public LichTrinh LichTrinh
		{
			get
			{
				return this._LichTrinh.Entity;
			}
			set
			{
				LichTrinh previousValue = this._LichTrinh.Entity;
				if (((previousValue != value) 
							|| (this._LichTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTrinh.Entity = null;
						previousValue.THEMTRAMDUNGCHANs.Remove(this);
					}
					this._LichTrinh.Entity = value;
					if ((value != null))
					{
						value.THEMTRAMDUNGCHANs.Add(this);
						this._MA_LICH_TRINH = value.MA_LICH_TRINH;
					}
					else
					{
						this._MA_LICH_TRINH = default(string);
					}
					this.SendPropertyChanged("LichTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAMDUNGCHAN_THEMTRAMDUNGCHAN", Storage="_TRAMDUNGCHAN", ThisKey="ID_TramDungChan", OtherKey="ID_TramDungChan", IsForeignKey=true)]
		public TRAMDUNGCHAN TRAMDUNGCHAN
		{
			get
			{
				return this._TRAMDUNGCHAN.Entity;
			}
			set
			{
				TRAMDUNGCHAN previousValue = this._TRAMDUNGCHAN.Entity;
				if (((previousValue != value) 
							|| (this._TRAMDUNGCHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAMDUNGCHAN.Entity = null;
						previousValue.THEMTRAMDUNGCHANs.Remove(this);
					}
					this._TRAMDUNGCHAN.Entity = value;
					if ((value != null))
					{
						value.THEMTRAMDUNGCHANs.Add(this);
						this._ID_TramDungChan = value.ID_TramDungChan;
					}
					else
					{
						this._ID_TramDungChan = default(string);
					}
					this.SendPropertyChanged("TRAMDUNGCHAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRAMDUNGCHAN")]
	public partial class TRAMDUNGCHAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_TramDungChan;
		
		private string _TEN_TramDungChan;
		
		private int _ID_DIADIEM;
		
		private EntitySet<THEMTRAMDUNGCHAN> _THEMTRAMDUNGCHANs;
		
		private EntitySet<Ve> _Ves;
		
		private EntitySet<Ve> _Ves1;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TramDungChanChanging(string value);
    partial void OnID_TramDungChanChanged();
    partial void OnTEN_TramDungChanChanging(string value);
    partial void OnTEN_TramDungChanChanged();
    partial void OnID_DIADIEMChanging(int value);
    partial void OnID_DIADIEMChanged();
    #endregion
		
		public TRAMDUNGCHAN()
		{
			this._THEMTRAMDUNGCHANs = new EntitySet<THEMTRAMDUNGCHAN>(new Action<THEMTRAMDUNGCHAN>(this.attach_THEMTRAMDUNGCHANs), new Action<THEMTRAMDUNGCHAN>(this.detach_THEMTRAMDUNGCHANs));
			this._Ves = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves), new Action<Ve>(this.detach_Ves));
			this._Ves1 = new EntitySet<Ve>(new Action<Ve>(this.attach_Ves1), new Action<Ve>(this.detach_Ves1));
			this._DiaDiem = default(EntityRef<DiaDiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TramDungChan", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_TramDungChan
		{
			get
			{
				return this._ID_TramDungChan;
			}
			set
			{
				if ((this._ID_TramDungChan != value))
				{
					this.OnID_TramDungChanChanging(value);
					this.SendPropertyChanging();
					this._ID_TramDungChan = value;
					this.SendPropertyChanged("ID_TramDungChan");
					this.OnID_TramDungChanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TramDungChan", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TEN_TramDungChan
		{
			get
			{
				return this._TEN_TramDungChan;
			}
			set
			{
				if ((this._TEN_TramDungChan != value))
				{
					this.OnTEN_TramDungChanChanging(value);
					this.SendPropertyChanging();
					this._TEN_TramDungChan = value;
					this.SendPropertyChanged("TEN_TramDungChan");
					this.OnTEN_TramDungChanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DIADIEM", DbType="Int NOT NULL")]
		public int ID_DIADIEM
		{
			get
			{
				return this._ID_DIADIEM;
			}
			set
			{
				if ((this._ID_DIADIEM != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DIADIEMChanging(value);
					this.SendPropertyChanging();
					this._ID_DIADIEM = value;
					this.SendPropertyChanged("ID_DIADIEM");
					this.OnID_DIADIEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAMDUNGCHAN_THEMTRAMDUNGCHAN", Storage="_THEMTRAMDUNGCHANs", ThisKey="ID_TramDungChan", OtherKey="ID_TramDungChan")]
		public EntitySet<THEMTRAMDUNGCHAN> THEMTRAMDUNGCHANs
		{
			get
			{
				return this._THEMTRAMDUNGCHANs;
			}
			set
			{
				this._THEMTRAMDUNGCHANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAMDUNGCHAN_Ve", Storage="_Ves", ThisKey="ID_TramDungChan", OtherKey="DIEMDON")]
		public EntitySet<Ve> Ves
		{
			get
			{
				return this._Ves;
			}
			set
			{
				this._Ves.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAMDUNGCHAN_Ve1", Storage="_Ves1", ThisKey="ID_TramDungChan", OtherKey="DIEMTRA")]
		public EntitySet<Ve> Ves1
		{
			get
			{
				return this._Ves1;
			}
			set
			{
				this._Ves1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TRAMDUNGCHAN", Storage="_DiaDiem", ThisKey="ID_DIADIEM", OtherKey="ID_DIADIEM", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.TRAMDUNGCHANs.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.TRAMDUNGCHANs.Add(this);
						this._ID_DIADIEM = value.ID_DIADIEM;
					}
					else
					{
						this._ID_DIADIEM = default(int);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THEMTRAMDUNGCHANs(THEMTRAMDUNGCHAN entity)
		{
			this.SendPropertyChanging();
			entity.TRAMDUNGCHAN = this;
		}
		
		private void detach_THEMTRAMDUNGCHANs(THEMTRAMDUNGCHAN entity)
		{
			this.SendPropertyChanging();
			entity.TRAMDUNGCHAN = null;
		}
		
		private void attach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TRAMDUNGCHAN = this;
		}
		
		private void detach_Ves(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TRAMDUNGCHAN = null;
		}
		
		private void attach_Ves1(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TRAMDUNGCHAN1 = this;
		}
		
		private void detach_Ves1(Ve entity)
		{
			this.SendPropertyChanging();
			entity.TRAMDUNGCHAN1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuyenDuong")]
	public partial class TuyenDuong : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_TUYEN;
		
		private string _TEN_TUYEN;
		
		private int _DIEM_DAU;
		
		private int _DIEM_CUOI;
		
		private double _KHOANG_CACH;
		
		private double _THOI_GIAN_DI_CHUYEN;
		
		private EntitySet<LichTrinh> _LichTrinhs;
		
		private EntityRef<DiaDiem> _DiaDiem;
		
		private EntityRef<DiaDiem> _DiaDiem1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_TUYENChanging(int value);
    partial void OnID_TUYENChanged();
    partial void OnTEN_TUYENChanging(string value);
    partial void OnTEN_TUYENChanged();
    partial void OnDIEM_DAUChanging(int value);
    partial void OnDIEM_DAUChanged();
    partial void OnDIEM_CUOIChanging(int value);
    partial void OnDIEM_CUOIChanged();
    partial void OnKHOANG_CACHChanging(double value);
    partial void OnKHOANG_CACHChanged();
    partial void OnTHOI_GIAN_DI_CHUYENChanging(double value);
    partial void OnTHOI_GIAN_DI_CHUYENChanged();
    #endregion
		
		public TuyenDuong()
		{
			this._LichTrinhs = new EntitySet<LichTrinh>(new Action<LichTrinh>(this.attach_LichTrinhs), new Action<LichTrinh>(this.detach_LichTrinhs));
			this._DiaDiem = default(EntityRef<DiaDiem>);
			this._DiaDiem1 = default(EntityRef<DiaDiem>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_TUYEN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_TUYEN
		{
			get
			{
				return this._ID_TUYEN;
			}
			set
			{
				if ((this._ID_TUYEN != value))
				{
					this.OnID_TUYENChanging(value);
					this.SendPropertyChanging();
					this._ID_TUYEN = value;
					this.SendPropertyChanged("ID_TUYEN");
					this.OnID_TUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TEN_TUYEN", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TEN_TUYEN
		{
			get
			{
				return this._TEN_TUYEN;
			}
			set
			{
				if ((this._TEN_TUYEN != value))
				{
					this.OnTEN_TUYENChanging(value);
					this.SendPropertyChanging();
					this._TEN_TUYEN = value;
					this.SendPropertyChanged("TEN_TUYEN");
					this.OnTEN_TUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM_DAU", DbType="Int NOT NULL")]
		public int DIEM_DAU
		{
			get
			{
				return this._DIEM_DAU;
			}
			set
			{
				if ((this._DIEM_DAU != value))
				{
					if (this._DiaDiem.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIEM_DAUChanging(value);
					this.SendPropertyChanging();
					this._DIEM_DAU = value;
					this.SendPropertyChanged("DIEM_DAU");
					this.OnDIEM_DAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEM_CUOI", DbType="Int NOT NULL")]
		public int DIEM_CUOI
		{
			get
			{
				return this._DIEM_CUOI;
			}
			set
			{
				if ((this._DIEM_CUOI != value))
				{
					if (this._DiaDiem1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIEM_CUOIChanging(value);
					this.SendPropertyChanging();
					this._DIEM_CUOI = value;
					this.SendPropertyChanged("DIEM_CUOI");
					this.OnDIEM_CUOIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHOANG_CACH", DbType="Float NOT NULL")]
		public double KHOANG_CACH
		{
			get
			{
				return this._KHOANG_CACH;
			}
			set
			{
				if ((this._KHOANG_CACH != value))
				{
					this.OnKHOANG_CACHChanging(value);
					this.SendPropertyChanging();
					this._KHOANG_CACH = value;
					this.SendPropertyChanged("KHOANG_CACH");
					this.OnKHOANG_CACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOI_GIAN_DI_CHUYEN", DbType="Float NOT NULL")]
		public double THOI_GIAN_DI_CHUYEN
		{
			get
			{
				return this._THOI_GIAN_DI_CHUYEN;
			}
			set
			{
				if ((this._THOI_GIAN_DI_CHUYEN != value))
				{
					this.OnTHOI_GIAN_DI_CHUYENChanging(value);
					this.SendPropertyChanging();
					this._THOI_GIAN_DI_CHUYEN = value;
					this.SendPropertyChanged("THOI_GIAN_DI_CHUYEN");
					this.OnTHOI_GIAN_DI_CHUYENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuyenDuong_LichTrinh", Storage="_LichTrinhs", ThisKey="ID_TUYEN", OtherKey="ID_TUYEN_DUONG")]
		public EntitySet<LichTrinh> LichTrinhs
		{
			get
			{
				return this._LichTrinhs;
			}
			set
			{
				this._LichTrinhs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TuyenDuong", Storage="_DiaDiem", ThisKey="DIEM_DAU", OtherKey="ID_DIADIEM", IsForeignKey=true)]
		public DiaDiem DiaDiem
		{
			get
			{
				return this._DiaDiem.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem.Entity = null;
						previousValue.TuyenDuongs.Remove(this);
					}
					this._DiaDiem.Entity = value;
					if ((value != null))
					{
						value.TuyenDuongs.Add(this);
						this._DIEM_DAU = value.ID_DIADIEM;
					}
					else
					{
						this._DIEM_DAU = default(int);
					}
					this.SendPropertyChanged("DiaDiem");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DiaDiem_TuyenDuong1", Storage="_DiaDiem1", ThisKey="DIEM_CUOI", OtherKey="ID_DIADIEM", IsForeignKey=true)]
		public DiaDiem DiaDiem1
		{
			get
			{
				return this._DiaDiem1.Entity;
			}
			set
			{
				DiaDiem previousValue = this._DiaDiem1.Entity;
				if (((previousValue != value) 
							|| (this._DiaDiem1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DiaDiem1.Entity = null;
						previousValue.TuyenDuongs1.Remove(this);
					}
					this._DiaDiem1.Entity = value;
					if ((value != null))
					{
						value.TuyenDuongs1.Add(this);
						this._DIEM_CUOI = value.ID_DIADIEM;
					}
					else
					{
						this._DIEM_CUOI = default(int);
					}
					this.SendPropertyChanged("DiaDiem1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.TuyenDuong = this;
		}
		
		private void detach_LichTrinhs(LichTrinh entity)
		{
			this.SendPropertyChanging();
			entity.TuyenDuong = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ve")]
	public partial class Ve : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ID_VE;
		
		private string _ID_LICH_TRINH;
		
		private double _TONG_TIEN;
		
		private string _NHAN_VIEN_TAO;
		
		private string _TRANG_THAI;
		
		private System.DateTime _NGAY_DAT_VE;
		
		private System.Nullable<int> _SOLUONG;
		
		private string _SDT;
		
		private string _TENKHACHHANG;
		
		private string _DIEMDON;
		
		private string _DIEMTRA;
		
		private string _HINHTHUCTHANHTOAN;
		
		private EntitySet<ChiTietVe> _ChiTietVes;
		
		private EntityRef<TRAMDUNGCHAN> _TRAMDUNGCHAN;
		
		private EntityRef<TRAMDUNGCHAN> _TRAMDUNGCHAN1;
		
		private EntityRef<LichTrinh> _LichTrinh;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_VEChanging(string value);
    partial void OnID_VEChanged();
    partial void OnID_LICH_TRINHChanging(string value);
    partial void OnID_LICH_TRINHChanged();
    partial void OnTONG_TIENChanging(double value);
    partial void OnTONG_TIENChanged();
    partial void OnNHAN_VIEN_TAOChanging(string value);
    partial void OnNHAN_VIEN_TAOChanged();
    partial void OnTRANG_THAIChanging(string value);
    partial void OnTRANG_THAIChanged();
    partial void OnNGAY_DAT_VEChanging(System.DateTime value);
    partial void OnNGAY_DAT_VEChanged();
    partial void OnSOLUONGChanging(System.Nullable<int> value);
    partial void OnSOLUONGChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnTENKHACHHANGChanging(string value);
    partial void OnTENKHACHHANGChanged();
    partial void OnDIEMDONChanging(string value);
    partial void OnDIEMDONChanged();
    partial void OnDIEMTRAChanging(string value);
    partial void OnDIEMTRAChanged();
    partial void OnHINHTHUCTHANHTOANChanging(string value);
    partial void OnHINHTHUCTHANHTOANChanged();
    #endregion
		
		public Ve()
		{
			this._ChiTietVes = new EntitySet<ChiTietVe>(new Action<ChiTietVe>(this.attach_ChiTietVes), new Action<ChiTietVe>(this.detach_ChiTietVes));
			this._TRAMDUNGCHAN = default(EntityRef<TRAMDUNGCHAN>);
			this._TRAMDUNGCHAN1 = default(EntityRef<TRAMDUNGCHAN>);
			this._LichTrinh = default(EntityRef<LichTrinh>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_VE", DbType="VarChar(128) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ID_VE
		{
			get
			{
				return this._ID_VE;
			}
			set
			{
				if ((this._ID_VE != value))
				{
					this.OnID_VEChanging(value);
					this.SendPropertyChanging();
					this._ID_VE = value;
					this.SendPropertyChanged("ID_VE");
					this.OnID_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LICH_TRINH", DbType="VarChar(128) NOT NULL", CanBeNull=false)]
		public string ID_LICH_TRINH
		{
			get
			{
				return this._ID_LICH_TRINH;
			}
			set
			{
				if ((this._ID_LICH_TRINH != value))
				{
					if (this._LichTrinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_LICH_TRINHChanging(value);
					this.SendPropertyChanging();
					this._ID_LICH_TRINH = value;
					this.SendPropertyChanged("ID_LICH_TRINH");
					this.OnID_LICH_TRINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TONG_TIEN", DbType="Float NOT NULL")]
		public double TONG_TIEN
		{
			get
			{
				return this._TONG_TIEN;
			}
			set
			{
				if ((this._TONG_TIEN != value))
				{
					this.OnTONG_TIENChanging(value);
					this.SendPropertyChanging();
					this._TONG_TIEN = value;
					this.SendPropertyChanged("TONG_TIEN");
					this.OnTONG_TIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHAN_VIEN_TAO", DbType="VarChar(128)")]
		public string NHAN_VIEN_TAO
		{
			get
			{
				return this._NHAN_VIEN_TAO;
			}
			set
			{
				if ((this._NHAN_VIEN_TAO != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNHAN_VIEN_TAOChanging(value);
					this.SendPropertyChanging();
					this._NHAN_VIEN_TAO = value;
					this.SendPropertyChanged("NHAN_VIEN_TAO");
					this.OnNHAN_VIEN_TAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANG_THAI", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string TRANG_THAI
		{
			get
			{
				return this._TRANG_THAI;
			}
			set
			{
				if ((this._TRANG_THAI != value))
				{
					this.OnTRANG_THAIChanging(value);
					this.SendPropertyChanging();
					this._TRANG_THAI = value;
					this.SendPropertyChanged("TRANG_THAI");
					this.OnTRANG_THAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAY_DAT_VE", DbType="DateTime NOT NULL")]
		public System.DateTime NGAY_DAT_VE
		{
			get
			{
				return this._NGAY_DAT_VE;
			}
			set
			{
				if ((this._NGAY_DAT_VE != value))
				{
					this.OnNGAY_DAT_VEChanging(value);
					this.SendPropertyChanging();
					this._NGAY_DAT_VE = value;
					this.SendPropertyChanged("NGAY_DAT_VE");
					this.OnNGAY_DAT_VEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOLUONG", DbType="Int")]
		public System.Nullable<int> SOLUONG
		{
			get
			{
				return this._SOLUONG;
			}
			set
			{
				if ((this._SOLUONG != value))
				{
					this.OnSOLUONGChanging(value);
					this.SendPropertyChanging();
					this._SOLUONG = value;
					this.SendPropertyChanged("SOLUONG");
					this.OnSOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="VarChar(15)")]
		public string SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENKHACHHANG", DbType="NVarChar(128)")]
		public string TENKHACHHANG
		{
			get
			{
				return this._TENKHACHHANG;
			}
			set
			{
				if ((this._TENKHACHHANG != value))
				{
					this.OnTENKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._TENKHACHHANG = value;
					this.SendPropertyChanged("TENKHACHHANG");
					this.OnTENKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMDON", DbType="VarChar(128)")]
		public string DIEMDON
		{
			get
			{
				return this._DIEMDON;
			}
			set
			{
				if ((this._DIEMDON != value))
				{
					if (this._TRAMDUNGCHAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIEMDONChanging(value);
					this.SendPropertyChanging();
					this._DIEMDON = value;
					this.SendPropertyChanged("DIEMDON");
					this.OnDIEMDONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMTRA", DbType="VarChar(128)")]
		public string DIEMTRA
		{
			get
			{
				return this._DIEMTRA;
			}
			set
			{
				if ((this._DIEMTRA != value))
				{
					if (this._TRAMDUNGCHAN1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnDIEMTRAChanging(value);
					this.SendPropertyChanging();
					this._DIEMTRA = value;
					this.SendPropertyChanged("DIEMTRA");
					this.OnDIEMTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHTHUCTHANHTOAN", DbType="NVarChar(128) NOT NULL", CanBeNull=false)]
		public string HINHTHUCTHANHTOAN
		{
			get
			{
				return this._HINHTHUCTHANHTOAN;
			}
			set
			{
				if ((this._HINHTHUCTHANHTOAN != value))
				{
					this.OnHINHTHUCTHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._HINHTHUCTHANHTOAN = value;
					this.SendPropertyChanged("HINHTHUCTHANHTOAN");
					this.OnHINHTHUCTHANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Ve_ChiTietVe", Storage="_ChiTietVes", ThisKey="ID_VE", OtherKey="ID_VE")]
		public EntitySet<ChiTietVe> ChiTietVes
		{
			get
			{
				return this._ChiTietVes;
			}
			set
			{
				this._ChiTietVes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAMDUNGCHAN_Ve", Storage="_TRAMDUNGCHAN", ThisKey="DIEMDON", OtherKey="ID_TramDungChan", IsForeignKey=true)]
		public TRAMDUNGCHAN TRAMDUNGCHAN
		{
			get
			{
				return this._TRAMDUNGCHAN.Entity;
			}
			set
			{
				TRAMDUNGCHAN previousValue = this._TRAMDUNGCHAN.Entity;
				if (((previousValue != value) 
							|| (this._TRAMDUNGCHAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAMDUNGCHAN.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._TRAMDUNGCHAN.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._DIEMDON = value.ID_TramDungChan;
					}
					else
					{
						this._DIEMDON = default(string);
					}
					this.SendPropertyChanged("TRAMDUNGCHAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRAMDUNGCHAN_Ve1", Storage="_TRAMDUNGCHAN1", ThisKey="DIEMTRA", OtherKey="ID_TramDungChan", IsForeignKey=true)]
		public TRAMDUNGCHAN TRAMDUNGCHAN1
		{
			get
			{
				return this._TRAMDUNGCHAN1.Entity;
			}
			set
			{
				TRAMDUNGCHAN previousValue = this._TRAMDUNGCHAN1.Entity;
				if (((previousValue != value) 
							|| (this._TRAMDUNGCHAN1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRAMDUNGCHAN1.Entity = null;
						previousValue.Ves1.Remove(this);
					}
					this._TRAMDUNGCHAN1.Entity = value;
					if ((value != null))
					{
						value.Ves1.Add(this);
						this._DIEMTRA = value.ID_TramDungChan;
					}
					else
					{
						this._DIEMTRA = default(string);
					}
					this.SendPropertyChanged("TRAMDUNGCHAN1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LichTrinh_Ve", Storage="_LichTrinh", ThisKey="ID_LICH_TRINH", OtherKey="MA_LICH_TRINH", IsForeignKey=true)]
		public LichTrinh LichTrinh
		{
			get
			{
				return this._LichTrinh.Entity;
			}
			set
			{
				LichTrinh previousValue = this._LichTrinh.Entity;
				if (((previousValue != value) 
							|| (this._LichTrinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LichTrinh.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._LichTrinh.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._ID_LICH_TRINH = value.MA_LICH_TRINH;
					}
					else
					{
						this._ID_LICH_TRINH = default(string);
					}
					this.SendPropertyChanged("LichTrinh");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_Ve", Storage="_NHANVIEN", ThisKey="NHAN_VIEN_TAO", OtherKey="USERNAME", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.Ves.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.Ves.Add(this);
						this._NHAN_VIEN_TAO = value.USERNAME;
					}
					else
					{
						this._NHAN_VIEN_TAO = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietVes(ChiTietVe entity)
		{
			this.SendPropertyChanging();
			entity.Ve = this;
		}
		
		private void detach_ChiTietVes(ChiTietVe entity)
		{
			this.SendPropertyChanging();
			entity.Ve = null;
		}
	}
	
	public partial class LayDanhSachXeCoTheGanResult
	{
		
		private System.Nullable<int> _ID_XE;
		
		public LayDanhSachXeCoTheGanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_XE", DbType="Int")]
		public System.Nullable<int> ID_XE
		{
			get
			{
				return this._ID_XE;
			}
			set
			{
				if ((this._ID_XE != value))
				{
					this._ID_XE = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
