<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLyBanVeXeKhach" Class="QuanLyNhaXeDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-86N3SME\SQL_KING;Initial Catalog=QuanLyBanVeXeKhach;Integrated Security=True" SettingsObjectName="DTO.Properties.Settings" SettingsPropertyName="QuanLyBanVeXeKhachConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietVe" Member="ChiTietVes">
    <Type Name="ChiTietVe">
      <Column Name="ID_VE" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_GHE" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="GHE_ChiTietVe" Member="GHE" ThisKey="ID_GHE" OtherKey="ID_GHE" Type="GHE" IsForeignKey="true" />
      <Association Name="Ve_ChiTietVe" Member="Ve" ThisKey="ID_VE" OtherKey="ID_VE" Type="Ve" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Xe" Member="Xes">
    <Type Name="Xe">
      <Column Name="ID_XE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BIEN_SO_XE" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="SO_GHE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_THEM" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Xe_LichTrinh" Member="LichTrinhs" ThisKey="ID_XE" OtherKey="ID_XE" Type="LichTrinh" />
    </Type>
  </Table>
  <Table Name="dbo.DiaDiem" Member="DiaDiems">
    <Type Name="DiaDiem">
      <Column Name="ID_DIADIEM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_TINH_THANH" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="DiaDiem_TuyenDuong" Member="TuyenDuongs" ThisKey="ID_DIADIEM" OtherKey="DIEM_DAU" Type="TuyenDuong" />
      <Association Name="DiaDiem_TuyenDuong1" Member="TuyenDuongs1" ThisKey="ID_DIADIEM" OtherKey="DIEM_CUOI" Type="TuyenDuong" />
      <Association Name="DiaDiem_TRAMDUNGCHAN" Member="TRAMDUNGCHANs" ThisKey="ID_DIADIEM" OtherKey="ID_DIADIEM" Type="TRAMDUNGCHAN" />
    </Type>
  </Table>
  <Table Name="dbo.GHE" Member="GHEs">
    <Type Name="GHE">
      <Column Name="ID_GHE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VI_TRI_NGOI" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="MA_LICH_TRINH" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="TRANG_THAI" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="GHE_ChiTietVe" Member="ChiTietVes" ThisKey="ID_GHE" OtherKey="ID_GHE" Type="ChiTietVe" />
      <Association Name="LichTrinh_GHE" Member="LichTrinh" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="LichTrinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LichTrinh" Member="LichTrinhs">
    <Type Name="LichTrinh">
      <Column Name="MA_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_TUYEN_DUONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KHOI_HANH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="KET_THUC" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="GIA_VE" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="ID_XE" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SOGHETRONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGAY_TAO_LICH_TRINH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="LichTrinh_GHE" Member="GHEs" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="GHE" />
      <Association Name="LichTrinh_THEMTRAMDUNGCHAN" Member="THEMTRAMDUNGCHANs" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="THEMTRAMDUNGCHAN" />
      <Association Name="LichTrinh_THONGKE" Member="THONGKEs" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="THONGKE" />
      <Association Name="LichTrinh_Ve" Member="Ves" ThisKey="MA_LICH_TRINH" OtherKey="ID_LICH_TRINH" Type="Ve" />
      <Association Name="Xe_LichTrinh" Member="Xe" ThisKey="ID_XE" OtherKey="ID_XE" Type="Xe" IsForeignKey="true" />
      <Association Name="TuyenDuong_LichTrinh" Member="TuyenDuong" ThisKey="ID_TUYEN_DUONG" OtherKey="ID_TUYEN" Type="TuyenDuong" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NHANVIEN" Member="NHANVIENs">
    <Type Name="NHANVIEN">
      <Column Name="USERNAME" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MAT_KHAU" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="HOTEN" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="SO_DT" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="GIOITINH" Type="System.String" DbType="NVarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="DIACHI" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="LOAINV" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Association Name="NHANVIEN_Ve" Member="Ves" ThisKey="USERNAME" OtherKey="NHAN_VIEN_TAO" Type="Ve" />
    </Type>
  </Table>
  <Table Name="dbo.TuyenDuong" Member="TuyenDuongs">
    <Type Name="TuyenDuong">
      <Column Name="ID_TUYEN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TEN_TUYEN" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DIEM_DAU" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="DIEM_CUOI" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="KHOANG_CACH" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="THOI_GIAN_DI_CHUYEN" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="TuyenDuong_LichTrinh" Member="LichTrinhs" ThisKey="ID_TUYEN" OtherKey="ID_TUYEN_DUONG" Type="LichTrinh" />
      <Association Name="DiaDiem_TuyenDuong" Member="DiaDiem" ThisKey="DIEM_DAU" OtherKey="ID_DIADIEM" Type="DiaDiem" IsForeignKey="true" />
      <Association Name="DiaDiem_TuyenDuong1" Member="DiaDiem1" ThisKey="DIEM_CUOI" OtherKey="ID_DIADIEM" Type="DiaDiem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THEMTRAMDUNGCHAN" Member="THEMTRAMDUNGCHANs">
    <Type Name="THEMTRAMDUNGCHAN">
      <Column Name="ID_TramDungChan" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MA_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="LichTrinh_THEMTRAMDUNGCHAN" Member="LichTrinh" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="LichTrinh" IsForeignKey="true" />
      <Association Name="TRAMDUNGCHAN_THEMTRAMDUNGCHAN" Member="TRAMDUNGCHAN" ThisKey="ID_TramDungChan" OtherKey="ID_TramDungChan" Type="TRAMDUNGCHAN" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.THONGKE" Member="THONGKEs">
    <Type Name="THONGKE">
      <Column Name="ID_THONG_KE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MA_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="SO_VE_DA_BAN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TONG_DOANH_THU" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="SO_GHE_CON_TRONG" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="LichTrinh_THONGKE" Member="LichTrinh" ThisKey="MA_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="LichTrinh" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.TRAMDUNGCHAN" Member="TRAMDUNGCHANs">
    <Type Name="TRAMDUNGCHAN">
      <Column Name="ID_TramDungChan" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TEN_TramDungChan" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ID_DIADIEM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="TRAMDUNGCHAN_THEMTRAMDUNGCHAN" Member="THEMTRAMDUNGCHANs" ThisKey="ID_TramDungChan" OtherKey="ID_TramDungChan" Type="THEMTRAMDUNGCHAN" />
      <Association Name="DiaDiem_TRAMDUNGCHAN" Member="DiaDiem" ThisKey="ID_DIADIEM" OtherKey="ID_DIADIEM" Type="DiaDiem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ve" Member="Ves">
    <Type Name="Ve">
      <Column Name="ID_VE" Type="System.String" DbType="VarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TENKHACHHANG" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ID_LICH_TRINH" Type="System.String" DbType="VarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="TONG_TIEN" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="NHAN_VIEN_TAO" Type="System.String" DbType="VarChar(128)" CanBeNull="true" />
      <Column Name="TRANG_THAI" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="NGAY_DAT_VE" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="SOLUONG" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="SDT" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Association Name="Ve_ChiTietVe" Member="ChiTietVes" ThisKey="ID_VE" OtherKey="ID_VE" Type="ChiTietVe" />
      <Association Name="LichTrinh_Ve" Member="LichTrinh" ThisKey="ID_LICH_TRINH" OtherKey="MA_LICH_TRINH" Type="LichTrinh" IsForeignKey="true" />
      <Association Name="NHANVIEN_Ve" Member="NHANVIEN" ThisKey="NHAN_VIEN_TAO" OtherKey="USERNAME" Type="NHANVIEN" IsForeignKey="true" />
    </Type>
  </Table>
</Database>